version: '3.8'

networks:
  net_cursojs:
    name: net_cursojs

    
services:
  curso_webserver:
    image: nginx:1.23-alpine
    container_name: curso_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./FRONT:/var/www/html
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      net_cursojs:

  curso_database:
    image: mysql:8.0
    container_name: curso_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=db_cursojs
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      net_cursojs:
  curso_pma:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: curso_pma
    environment:
      - PMA_HOST=curso_database
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=4048M
      - UPLOAD_MAX_FILESIZE=512M
      - MAX_EXECUTION_TIME=38000
    ports:
      - "8005:80"
    networks:
      net_cursojs:
        
volumes:
  mysqldb: